### ISSUE TITLE
ModuleNotFoundError: No module named 'github_com.TheThingsNetwork'

### ISSUE THREAD

**Issue by concaoccc** [TheThingsNetwork/python-app-sdk#12]
I used python3 in China, and used "pip install ttn" to install the package. But, when I run the code provided as exmaple, some errors happend:
Traceback (most recent call last):
  File "E:/python_code/LoRa_AT/test.py", line 2, in <module>
    from ttn import MQTTClient as mqtt_client
  File "C:\Users\caocongcong\AppData\Local\Continuum\Anaconda3\lib\site-packages\ttn\__init__.py", line 1, in <module>
    from .ttnmqtt import MQTTClient
  File "C:\Users\caocongcong\AppData\Local\Continuum\Anaconda3\lib\site-packages\ttn\ttnmqtt.py", line 12, in <module>
    import github_com.TheThingsNetwork.api.discovery.discovery_pb2_grpc as disco
ModuleNotFoundError: No module named 'github_com.TheThingsNetwork'

**Comment by egourlao** [comment]
Thanks for your bug report! I can reproduce it on my side. Looks like a regular package import error. I'll have a look at it in the next few days!

**Comment by egourlao** [comment]
Version 2.1.1 of the SDK was just released, resolving this issue! 🎉 Thanks for reporting!

**Comment by zmarwa** [comment]
I have an issue :

handler = ttn.HandlerClient(app_id, access_key)
AttributeError: 'module' object has no attribute 'HandlerClient'

when using this library with python2.7 . is it compatibility issue ? any solution plz

command: "pip install ttn" working without any error

and 

"pip show ttn"

Name: ttn
Version: 2.1.1
Summary: The Things Network Client
Home-page: https://github.com/TheThingsNetwork/python-app-sdk
Author: Emmanuelle Lejeail
Author-email: emmanuelle@thethingsindustries.com
License: MIT
Location: /home/user/.local/lib/python2.7/site-packages
Requires: python-jose, google-cloud, paho-mqtt, google-api-python-client, grpcio, protobuf, events

**Comment by egourlao** [comment]
Hi @zmarwa, I'm unable to reproduce this error:

```
$ docker run -it python:2 bash
(docker)$ pip install ttn
(docker)$ python2
Python 2.7.14 (default, Mar 14 2018, 18:21:57)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ttn
>>> handler = ttn.HandlerClient("<application>", "<application key>")
>>>
```

Could you give us more information to help us isolate the issue? You might also want to check that you do not have any naming conflict, such as a submodule in the directory that would be called `ttn`.

**Comment by mtausig** [comment]
@zmarwa I had the very same error as you. My problem was, that my scipt was called `ttn.py` whch go mixed up with the `ttn` module.
