### ISSUE TITLE
Evaluate Google Cloud dependencies

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/python-app-sdk#14]
Remove if necessary.

**Comment by gtmtg** [comment]
Hi! Just curious, any progress on this?

**Comment by egourlao** [comment]
No progress on this indeed for the moment, indeed. Those dependencies were added during the protocol buffer transpiling, when transpiling `TheThingsNetwork/api` handler protos to Python - steps which are also unfortunately not documented.

For anyone that wants to look into this, here would be a few ideas to tackle the problem:
+ Recreate (and document) the transpilation process
+ Compare it to how other projects using `protobuf`, and see if they had similar dependencies problem - try to figure out the root cause and see what are the options :)
+ If those dependencies are unavoidable, have a look at alternative protobuf transpilers for Python, and see if they solve the problem while offering reasonable tradeoffs.
