### ISSUE TITLE
RuntimeError: unexpected disconnection

### ISSUE THREAD

**Issue by mehrdadh** [TheThingsNetwork/python-app-sdk#26]
The client does not reconnect to the server if any unexpected error happened. I believe it's because of [this line](https://github.com/TheThingsNetwork/python-app-sdk/blob/7f2e8e618ed59bcacbb2370385b1f34ad02103e1/ttn/ttnmqtt.py#L101).

I removed this line in ttn python package and it worked fine.

**Comment by gtmtg** [comment]
FYI, getting the same error. When you removed the line, did you also add logic to reconnect? Can't see where that would happen automatically.
