### ISSUE TITLE
Unable to connect with TTI

### ISSUE THREAD

**Issue by krimvp** [TheThingsNetwork/python-app-sdk#32]
The connection with TTI won't work  (only with TTN) using this wrapper. There seems to be an issue in the way the grpc safe connection is made in python.

In order to make it work, the secure connection should be swapped for an insecure one until the certificate is supported for python.

This is a workaround and by no means the proper way to do it but it is a showstopper if anyone is using TTI as of now with any wrapper other than the Go one

**Comment by krimvp** [comment]
Made a temporary workaround, feel free to check it at https://github.com/krimvp/python-app-sdk/tree/issues/32_insecure_connection_workaround_tti

**Comment by johanstokking** [comment]
Meh.

Can you file a PR maybe with a proper configuration option to use an insecure channel?

**Comment by krimvp** [comment]
I just submitted a more decent implementation, also the PR

**Comment by krimvp** [comment]
I am closing this issue as PR #33  has introduced an option to connect (although using an insecure channel). 

For reference (if anyone has any issues with this in the future). The normal implementation that works with the secure channel (and for the open service TTN) is not working on TTI due to a problem of configuration in the infra (confirmed by support)
