### ISSUE TITLE
Downlink message send() does not work

### ISSUE THREAD

**Issue by antonpperez** [TheThingsNetwork/python-app-sdk#34]
## Expected Behavior
When making use of ```client.send(dev_id="something", pay="something else")``` I would expect the downlink message to be scheduled to be sent later (since default behavior is "replace").
Changing the scheduling strategy to "last" or "first" does not help either
 
## Current Behavior
The downlink_callback is working, that means the client detects something is being sent but it never arrives to the platform (nor the final device).
In order to check this I have MQTTBox connected and subscribed to **#/down/#** and **#/scheduled** and the message that I send it never appears. It does not appear in the console "Data" tab either

**Sending it from the web console does work** (I can see it in both the console and in MQTTBox)

## Example
```
import ttn

def downlink_callback(mid, client):
  print("Received downlink with id ", mid)

handler = ttn.HandlerClient("SOME_APP_ID", "SOME_ACCESS_KEY", discovery_address="something.thethings.industries:1900", insecure_channel=True)
mqtt_client = handler.data()
mqtt_client.set_downlink_callback(downlink_callback)
mqtt_client.send(dev_id="some_dev_id", pay="SOME_PAYLOAD", conf=True)
time.sleep(10)
mqtt_client.close()
```

**Comment by antonpperez** [comment]
Another interesting thing to mention (and bear in mind I'm a newbie here in TTN/MQTT related stuff) is that the message id for the callback always start at 1 for the specific client that I open. If I send several messages before closing the connection then the id increases every time, but always restarts at 1.

**Comment by johanstokking** [comment]
@antonpperez thanks for reporting.

Can you print the JSON to be published after [this line](https://github.com/TheThingsNetwork/python-app-sdk/blob/master/ttn/ttnmqtt.py#L159) ? 

Note that there's no difference between TTN and TTI here; I'm updating your title.

**Comment by antonpperez** [comment]
Hi there, sorry for the late reply.

An example of that line could be this one
```{"port": 1, "confirmed": false, "schedule": "replace", "payload_raw": "01080003000001805101003C000807100ED80E000F460F7864938C"}```
The string is the hex string exactly the same way it works if I send it using the console

I have spent half Friday trying to make it work, I have tried to send both a HEX string and a base64 with no luck. In both cases, I tried using lowercase and uppercase characters.

I have also tried to add the key ```dev_id``` in the payload of the message and again with no luck.

Another thing I tried to make work was to use the ```res.wait_for_publish()``` again with no luck.

In order to see if I receive the messages, I am using MQTTBox and the web console sniffing all the data of the application I am connecting to. I receive both messages when sending it from the console itself (I also tried the nodejs sdk and also works fine). The issue seems to happen only with the Python client.

**Comment by Sypheos** [comment]
Hello @antonpperez 

Please call the `.connect()` method of the MQTT client before sending the downlinks as shown in the README.md

The SDK doesn't trigger any exception when it is not connected, will open a PR.

**Comment by antonpperez** [comment]
Hi there, the error still persists even calling client.connect() just before the sending.
I also had tried that before

**Comment by Sypheos** [comment]
Your payload might be too long and remember to encode your payload in base64.

See [doc](https://www.thethingsnetwork.org/docs/applications/mqtt/api.html)

**Comment by antonpperez** [comment]
How am I supposed to know if the payload is too long? I have sent the same from both the console and nodejs sdks and in both cases it works.

According to https://github.com/TheThingsNetwork/python-app-sdk/blob/master/DOCUMENTATION.md#send the payload might be:

"payload: the payload of the message to be published to the broker. It can be **an hexadecimal string, **a** base64 string** like AQ== (this will send the raw payload 01 to your device) **or** a **dictionary** of JSON nature."

I also have tried the base64 encoded string and for both the hexadecimal and base64 strings I have tried the uppercase and lowercase variants

**Comment by Sypheos** [comment]
The console take direct Hex as field same for the node SDK. They expect Hex as raw representation for the console and as a string for the node SDK.
Looking at the code the SDK only handles base64 or object (which will be marshalled as JSON in the payload fields).
There is no uppercase / lowercase for base664, capital letter matters.

**Comment by johanstokking** [comment]
@Sypheos can you update the documentation please? We do not accept hex.

**Comment by Sypheos** [comment]
Will do

**Comment by antonpperez** [comment]
Hi there, I can confirm that the issue was indeed sending the hex string  instead of the base64 and in the second case, I was missing the connect().

**Comment by johanstokking** [comment]
Thanks for confirming @antonpperez
