### ISSUE TITLE
Documentation error MQTTClient.send

### ISSUE THREAD

**Issue by abablok** [TheThingsNetwork/python-app-sdk#35]
In the documentation it says 
`MQTTClient.send(dev_id, payload, port=1, confirmation=False, schedule="replace")`
but the definition is
` MQTTClient.send(self, dev_id, pay, port=1, conf=False, sched="replace")`

**Comment by htdvisser** [comment]
With The Things Network V2 shut down, we're going to archive this repository. This issue will be locked.
