### ISSUE TITLE
The MQTT server uses MQTTS, but the client won't accept the TLS certificate

### ISSUE THREAD

**Issue by skyluke86** [TheThingsNetwork/python-app-sdk#36]
Is it possible to fix the MQTTS connection please?

**Comment by johanstokking** [comment]
Can you elaborate the issue? What is the error you're seeing? Is this on public community network or a private network?

**Comment by skyluke86** [comment]
At the end of DOCUMENTATION.md in section Troubleshooting, there is written the title: The MQTT server uses MQTTS, but the client won't accept the TLS certificate
I'm testing on TTN and there is the MQTT over TLS. [TTN MQTTS](https://www.thethingsnetwork.org/docs/applications/mqtt/api.html)
And i did some test with wireshark and as it is written in the doc, there is no packet encryption. Something in the code that does not work properly. Is it possible to fix? Thanks

**Comment by htdvisser** [comment]
With The Things Network V2 shut down, we're going to archive this repository. This issue will be locked.
