### ISSUE TITLE
Update Python version on Travis to 3.6

### ISSUE THREAD

**Issue by egourlao** [TheThingsNetwork/python-app-sdk#5]

**Comment by emmlejeail** [comment]
Done, CI now tests 3.6, 3.5 and 2.7. I got rid of 3.4.

**Comment by egourlao** [comment]
Please respect the scope of each PR, another PR could have been used for this rather than piggybacking this to #4.

**Comment by emmlejeail** [comment]
Okay, got it! I didn't know creating a whole PR was more logical for this kind of issue
